### ISSUE TITLE
Weird alert comes up.

### ISSUE THREAD

**Issue by tuxbotix** [HULKs/hulks.github.io#72]
![relative_map_fix11](https://user-images.githubusercontent.com/6742239/30737363-9cdea8fe-9f86-11e7-848e-cdce4eb8f852.png)

Also an error on console,
```
api.longurl.org/v2/expand?format=json&url=https://youtu.be/bD5SSVylqps&callback=jQuery30005681149922271804_1506071318025 
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
```

**Comment by eladkarako** [comment]
happen to came across this.
this API won't work anymore. try use either of those:
<code>http&#x003A;//9inchurl.com/api.php?url=</code>
<code>https&#x003A;//unshorten.me/s/</code>

( used in https://github.com/eladkarako/chrome_extensions/tree/store/Remove-Redirects-Plus )
